# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial01.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 591)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/bottle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background: black;\n"
"color: white;\n"
"font: bold 14px Arial;")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(790, 80))
        self.groupBox.setStyleSheet("groupBox[color:rgb(170, 85, 255)]")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Com_Port = QtWidgets.QComboBox(self.groupBox)
        self.Com_Port.setMinimumSize(QtCore.QSize(0, 30))
        self.Com_Port.setStyleSheet("QComboBox{background: rgb(75, 75, 75);\n"
"color: white;\n"
"border-radius: 3px; }\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid yellow;   /* 整个下拉窗体的边框 */\n"
"    color: black;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: rgb(0, 170, 255);   /* 整个下拉窗体被选中项的背景色 */\n"
"}\n"
"")
        self.Com_Port.setObjectName("Com_Port")
        self.horizontalLayout_2.addWidget(self.Com_Port)
        self.Com_Band = QtWidgets.QComboBox(self.groupBox)
        self.Com_Band.setEnabled(True)
        self.Com_Band.setMinimumSize(QtCore.QSize(0, 30))
        self.Com_Band.setBaseSize(QtCore.QSize(0, 0))
        self.Com_Band.setStyleSheet("QComboBox{background: rgb(75, 75, 75);\n"
"color: white;\n"
"border-radius: 3px; }\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid yellow;   /* 整个下拉窗体的边框 */\n"
"    color: black;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: rgb(0, 170, 255);   /* 整个下拉窗体被选中项的背景色 */\n"
"}\n"
"")
        self.Com_Band.setObjectName("Com_Band")
        self.Com_Band.addItem("")
        self.Com_Band.addItem("")
        self.Com_Band.addItem("")
        self.Com_Band.addItem("")
        self.Com_Band.addItem("")
        self.horizontalLayout_2.addWidget(self.Com_Band)
        self.Open_Com = QtWidgets.QPushButton(self.groupBox)
        self.Open_Com.setMinimumSize(QtCore.QSize(90, 30))
        self.Open_Com.setMouseTracking(False)
        self.Open_Com.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);}")
        self.Open_Com.setAutoDefault(True)
        self.Open_Com.setObjectName("Open_Com")
        self.horizontalLayout_2.addWidget(self.Open_Com)
        self.refesh_Com = QtWidgets.QPushButton(self.groupBox)
        self.refesh_Com.setMinimumSize(QtCore.QSize(0, 30))
        self.refesh_Com.setMouseTracking(False)
        self.refesh_Com.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);;}\n"
"")
        self.refesh_Com.setObjectName("refesh_Com")
        self.horizontalLayout_2.addWidget(self.refesh_Com)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Data_Display = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Data_Display.setFont(font)
        self.Data_Display.setStyleSheet("border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);")
        self.Data_Display.setObjectName("Data_Display")
        self.verticalLayout_4.addWidget(self.Data_Display)
        self.Send_Data_Dsiplay = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Send_Data_Dsiplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Send_Data_Dsiplay.setMouseTracking(False)
        self.Send_Data_Dsiplay.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Send_Data_Dsiplay.setStyleSheet("border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);")
        self.Send_Data_Dsiplay.setTabChangesFocus(False)
        self.Send_Data_Dsiplay.setObjectName("Send_Data_Dsiplay")
        self.verticalLayout_4.addWidget(self.Send_Data_Dsiplay)
        self.verticalLayout_4.setStretch(0, 3)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(200, 480))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_4 = QtWidgets.QSplitter(self.frame)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.Data_clear = QtWidgets.QPushButton(self.splitter_4)
        self.Data_clear.setMinimumSize(QtCore.QSize(0, 30))
        self.Data_clear.setMaximumSize(QtCore.QSize(90, 30))
        self.Data_clear.setMouseTracking(False)
        self.Data_clear.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);}")
        self.Data_clear.setObjectName("Data_clear")
        self.Data_save = QtWidgets.QPushButton(self.splitter_4)
        self.Data_save.setMinimumSize(QtCore.QSize(0, 30))
        self.Data_save.setMaximumSize(QtCore.QSize(90, 30))
        self.Data_save.setMouseTracking(False)
        self.Data_save.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);}")
        self.Data_save.setObjectName("Data_save")
        self.verticalLayout_2.addWidget(self.splitter_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton = QtWidgets.QRadioButton(self.splitter)
        self.radioButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_2.setAutoFillBackground(False)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.splitter)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setStyleSheet("")
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_4.setAutoFillBackground(False)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.splitter_6 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.checkBox_4 = QtWidgets.QCheckBox(self.splitter_6)
        self.checkBox_4.setMinimumSize(QtCore.QSize(80, 30))
        self.checkBox_4.setMaximumSize(QtCore.QSize(80, 30))
        self.checkBox_4.setObjectName("checkBox_4")
        self.SendData_Timer = QtWidgets.QCheckBox(self.splitter_6)
        self.SendData_Timer.setMinimumSize(QtCore.QSize(80, 30))
        self.SendData_Timer.setMaximumSize(QtCore.QSize(80, 30))
        self.SendData_Timer.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);}")
        self.SendData_Timer.setObjectName("SendData_Timer")
        self.verticalLayout_6.addWidget(self.splitter_6)
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.spinBox = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox.setAcceptDrops(True)
        self.spinBox.setStyleSheet("border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);\n"
"")
        self.spinBox.setMaximum(9999999)
        self.spinBox.setProperty("value", 1000)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.splitter_3)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.splitter_3)
        self.Send_Command_Dsiplay = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.Send_Command_Dsiplay.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Send_Command_Dsiplay.setStyleSheet("border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);")
        self.Send_Command_Dsiplay.setObjectName("Send_Command_Dsiplay")
        self.verticalLayout_6.addWidget(self.Send_Command_Dsiplay)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.splitter_5 = QtWidgets.QSplitter(self.frame)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.Send_Data = QtWidgets.QPushButton(self.splitter_5)
        self.Send_Data.setMinimumSize(QtCore.QSize(90, 30))
        self.Send_Data.setMaximumSize(QtCore.QSize(90, 30))
        self.Send_Data.setMouseTracking(False)
        self.Send_Data.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);}")
        self.Send_Data.setObjectName("Send_Data")
        self.SendData_clear = QtWidgets.QPushButton(self.splitter_5)
        self.SendData_clear.setMinimumSize(QtCore.QSize(90, 30))
        self.SendData_clear.setMaximumSize(QtCore.QSize(90, 30))
        self.SendData_clear.setMouseTracking(False)
        self.SendData_clear.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);}")
        self.SendData_clear.setObjectName("SendData_clear")
        self.verticalLayout_2.addWidget(self.splitter_5)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 240))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Com_Port_Usb = QtWidgets.QComboBox(self.groupBox_4)
        self.Com_Port_Usb.setMinimumSize(QtCore.QSize(0, 30))
        self.Com_Port_Usb.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Com_Port_Usb.setStyleSheet("QComboBox{background: rgb(75, 75, 75);\n"
"color: white;\n"
"border-radius: 3px; }\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid yellow;   /* 整个下拉窗体的边框 */\n"
"    color: black;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: rgb(0, 170, 255);   /* 整个下拉窗体被选中项的背景色 */\n"
"}\n"
"")
        self.Com_Port_Usb.setObjectName("Com_Port_Usb")
        self.verticalLayout_8.addWidget(self.Com_Port_Usb)
        self.Com_Band_Usb = QtWidgets.QComboBox(self.groupBox_4)
        self.Com_Band_Usb.setMinimumSize(QtCore.QSize(0, 30))
        self.Com_Band_Usb.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Com_Band_Usb.setStyleSheet("QComboBox{background: rgb(75, 75, 75);\n"
"color: white;\n"
"border-radius: 3px; }\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid yellow;   /* 整个下拉窗体的边框 */\n"
"    color: black;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: rgb(0, 170, 255);   /* 整个下拉窗体被选中项的背景色 */\n"
"}\n"
"")
        self.Com_Band_Usb.setObjectName("Com_Band_Usb")
        self.Com_Band_Usb.addItem("")
        self.Com_Band_Usb.addItem("")
        self.Com_Band_Usb.addItem("")
        self.Com_Band_Usb.addItem("")
        self.Com_Band_Usb.addItem("")
        self.verticalLayout_8.addWidget(self.Com_Band_Usb)
        self.Open_Usb = QtWidgets.QPushButton(self.groupBox_4)
        self.Open_Usb.setMinimumSize(QtCore.QSize(90, 30))
        self.Open_Usb.setMaximumSize(QtCore.QSize(1000, 30))
        self.Open_Usb.setStyleSheet("QPushButton:hover {background:qlineargradient(x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #47a7ed, stop: 1 #a967b2);}\n"
"QPushButton:pressed {background-color: rgb(0, 170, 255);}\n"
"QPushButton{border-radius: 3px; \n"
"background-color: rgb(75, 75, 75);;}\n"
"")
        self.Open_Usb.setObjectName("Open_Usb")
        self.verticalLayout_8.addWidget(self.Open_Usb)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_8.addWidget(self.checkBox_5)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.setStretch(0, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Open_Com.clicked.connect(MainWindow.Open_Com_Click) # type: ignore
        self.Send_Data.clicked.connect(MainWindow.Send_Data_Click) # type: ignore
        self.SendData_clear.clicked.connect(self.Send_Data_Dsiplay.clear) # type: ignore
        self.Data_clear.clicked.connect(self.Data_Display.clear) # type: ignore
        self.refesh_Com.clicked.connect(MainWindow.refesh_Com_Click) # type: ignore
        self.Data_save.clicked.connect(MainWindow.Save_Data_Click) # type: ignore
        self.Open_Usb.clicked.connect(MainWindow.Open_Usb_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口调试"))
        self.groupBox.setTitle(_translate("MainWindow", "串口配置"))
        self.Com_Band.setItemText(0, _translate("MainWindow", "115200"))
        self.Com_Band.setItemText(1, _translate("MainWindow", "57600"))
        self.Com_Band.setItemText(2, _translate("MainWindow", "38400"))
        self.Com_Band.setItemText(3, _translate("MainWindow", "19200"))
        self.Com_Band.setItemText(4, _translate("MainWindow", "9600"))
        self.Open_Com.setText(_translate("MainWindow", "打开串口"))
        self.refesh_Com.setText(_translate("MainWindow", "刷新串口"))
        self.Data_Display.setPlaceholderText(_translate("MainWindow", "显示接收数据"))
        self.Send_Data_Dsiplay.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Send_Data_Dsiplay.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Send_Data_Dsiplay.setPlaceholderText(_translate("MainWindow", "输入发送数据"))
        self.Data_clear.setText(_translate("MainWindow", "清空数据"))
        self.Data_save.setText(_translate("MainWindow", "保存日志"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收设置"))
        self.radioButton.setText(_translate("MainWindow", "HEX"))
        self.radioButton_2.setText(_translate("MainWindow", "ASCII"))
        self.checkBox.setText(_translate("MainWindow", "自动换行"))
        self.checkBox_2.setText(_translate("MainWindow", "显示发送"))
        self.checkBox_3.setText(_translate("MainWindow", "显示时间"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送设置"))
        self.radioButton_3.setText(_translate("MainWindow", "HEX"))
        self.radioButton_4.setText(_translate("MainWindow", "ASCII"))
        self.checkBox_4.setText(_translate("MainWindow", "添加指令"))
        self.SendData_Timer.setText(_translate("MainWindow", "重复发送"))
        self.label.setText(_translate("MainWindow", "ms"))
        self.Send_Command_Dsiplay.setPlaceholderText(_translate("MainWindow", "指令注意包含替换参数<pa>"))
        self.Send_Data.setText(_translate("MainWindow", "发送数据"))
        self.SendData_clear.setText(_translate("MainWindow", "清空数据"))
        self.groupBox_4.setTitle(_translate("MainWindow", "选择设备"))
        self.Com_Band_Usb.setItemText(0, _translate("MainWindow", "115200"))
        self.Com_Band_Usb.setItemText(1, _translate("MainWindow", "57600"))
        self.Com_Band_Usb.setItemText(2, _translate("MainWindow", "38400"))
        self.Com_Band_Usb.setItemText(3, _translate("MainWindow", "19200"))
        self.Com_Band_Usb.setItemText(4, _translate("MainWindow", "9600"))
        self.Open_Usb.setText(_translate("MainWindow", "打开设备"))
        self.checkBox_5.setText(_translate("MainWindow", "自动发送"))
import bottle_rc
